---
# tasks file for aws-ec2-provisioning/
- fail: msg="The minimum Ansible version required to run is 2.0.1. To upgrade run 'sudo pip install --upgrade ansible'."
  when: ansible_version.major|int != 2 and ansible_version.minor|int < 0 and ansible_version.revision|int < 1

- include: tasks/terminate.yml
  when: {{ item.state }} == "absent"
  with_items: {{ instances }}

- include: tasks/create.yml
  when: {{ item.state }} == "present"
  with_items: {{ instances }}

