---
- name: terminate instances
  ec2:
    instance_tags: "{{ item.aws_resource_tags | default(omit) }}"
    state: "{{ item.state | default('absent') }}"
    region: "{{ item.ec2_region }}"
  with_items: "{{ instances }}"
  register: ec2

